dialog_lines = [
    "Pagi itu, sinar matahari lembut menerobos jendela toko kue tua di Bakery Street, Paradise.",
    "Tempat itu sudah lama ditinggalkan—penuh debu, kain penutup lusuh, dan aroma kenangan yang nyaris terlupakan.",
    "Sudah bertahun-tahun berlalu sejak pintu toko itu terakhir kali dibuka.",
    "Sebuah pintu tua berderit... dan Evan melangkah masuk.",
    "Debu berterbangan di setiap langkahnya.",
    "Meja-meja tertutup kain putih kusam, penuh jejak waktu.",
    "Oven tua itu masih berdiri di sudut ruangan, seolah menunggu seseorang kembali.",
    "Evan berhenti di tengah toko, memandang sekeliling dengan perasaan campur aduk.",
    "Tempat ini... masih sama persis seperti kenangan masa kecilnya.",
    "Lalu suara langkah kaki terdengar pelan dari belakang.",
    "Seorang pria paruh baya masuk—Paman Charlie.",
    "'Akhirnya kau datang, Evan,' ucapnya dengan senyum hangat.",
    "Evan terdiam, masih diliputi keraguan dan nostalgia.",
    "Toko ini telah lama mati... sepi... hilang dari ingatan warga Paradise.",
    "Mampukah ia benar-benar menghidupkannya kembali?",
    "Charlie meletakkan sebuah kotak kayu tua di atas meja.",
    "Di dalamnya terdapat buku resep peninggalan nenek Evan.",
    "'Nenekmu percaya padamu,' ujar Charlie lembut.",
    "'Dia selalu bilang bahwa kau punya kemampuan untuk membuat orang bahagia lewat kue.'",
    "Evan membuka halaman demi halaman, melihat tulisan tangan yang ia kenal sejak kecil.",
    "Kenangan aroma kue coklat hangat tiba-tiba memenuhi kepalanya.",
    "Charlie menatapnya serius.",
    "'Paradise berubah sejak toko ini tutup. Orang-orang kehilangan tempat untuk merasa pulang.'",
    "'Jika ada yang bisa menghidupkan kembali Bakery of Dreams... itu kau, Evan.'",
    "'Kau punya waktu 40 hari. Tunjukkan bahwa toko ini masih bisa bersinar.'",
    "Evan menarik napas dalam.",
    "Untuk pertama kalinya—ia melihat masa depan, bukan masa lalu.",
    "'Aku akan mencobanya... tidak, aku akan berhasil,' tekad Evan.",
    "Dan pagi itu, di ruangan penuh debu dan kenangan, perjalanan baru dimulai.",
    "Perjalanan untuk menghidupkan kembali sebuah toko kue yang hampir terlupakan.",
    "Perjalanan untuk membawa kembali kebahagiaan ke Paradise.",
    "Dan perjalanan itu dimulai... dengan satu langkah kecil dari Evan."
];

bad_dialog_lines = [
	"Empat puluh hari berlalu.",
	"Paradise tetap sunyi-lebih sunyi daripada sebelumnya.",
	"Toko itu kembali gelap, sama seperti sebelum semua mimpi itu dimulai.",
	"Peralatan berserakan tanpa tenaga untuk bergerak.",
	"Aroma kue yang dulu sempat memberi harapan kini telah hilang-lenyap seperti embun pagi yang tersapu matahari.",
	"Di depan toko, seseorang duduk sendirian, menatap buku resep tua yang kini terasa lebih berat dari sebelumnya.",
	"Ia sudah berusaha. Ia sudah mencoba. Lebih keras daripada siapapun.",
	"Namun pelanggan tak pernah datang.",
	"Reputasi tak pernah tumbuh.",
	"Dan waktu… tidak pernah menunggu.",
	"Langkah kaki pelan terdengar di belakangnya.",
	"Seseorang berdiri di sana, membawa empati yang tak mampu menghapus luka.",
	"Tidak ada kata-kata yang cukup untuk menenangkan kegagalan.",
	"Seseorang itu menghela napas panjang—napas yang terdengar seperti perpisahan.",
	"Pemilik impian itu berdiri perlahan dan menatap toko yang pernah ia percayai.",
	"Sekali lagi… hanya sekali lagi… sebelum semuanya benar-benar berakhir.",
	"Pintu ditutup perlahan, seolah takut merusak keheningan yang tersisa.",
	"Tanda 'CLOSED' kembali tergantung di jendela-dingin, sunyi, dan final.",
	"Dan bersama pintu yang tertutup itu… harapan kecil Paradise ikut meredup.",
	"Toko itu menjadi kenangan lagi.",
	"Sebuah tempat yang hampir kembali hidup, hampir menjadi legenda, hampir menerangi kota kecil itu.",
	"Namun dunia berubah terlalu cepat.",
	"Dan tak semua mimpi diberi kesempatan kedua."
]
good_dialog_lines = [
	"Empat puluh hari kemudian, Paradise berubah.",
	"Kehidupan kembali mengalir, seperti aroma kue hangat yang memenuhi udara pagi itu.",
	"Alun-alun kota dipenuhi warna-warni dekorasi yang berkilau diterpa sinar matahari.",
	"Festival Kue Tahunan—yang lama menghilang—akhirnya kembali diadakan.",
	"Stand-stand makanan berjajar rapi, musik mengalun lembut, dan warga Paradise tersenyum seperti masa-masa indah dahulu.",
	"Di tengah keramaian itu, satu tempat menarik perhatian semua orang.",
	"Bakery of Dreams.",
	"Stand kecil itu dipenuhi warga yang tak henti memesan.",
	"Kue-kue yang disajikan sederhana… namun setiap gigitannya seperti membawa kembali rasa rumah.",
	"Aroma manis yang keluar dari rak pemanas seolah membangkitkan kenangan seluruh kota.",
	"Evan bekerja tanpa henti, tetapi untuk pertama kalinya, ia tidak merasa lelah.",
	"Ia merasa hidup.",
	"Nama seseorang dipanggil melalui pengeras suara.",
	"Walikota memanggil Evan naik ke panggung.",
	"Sorakan warga memenuhi udara ketika ia melangkah maju.",
	"Langkahnya kini mantap—bukan sebagai pemuda yang ragu, tetapi sebagai seseorang yang telah membawa harapan kembali.",
	"Di atas panggung, seseorang menyerahkan sebuah surat tua.",
	"Sebuah surat dari neneknya.",
	"Kata-katanya sederhana, tetapi menembus hati:",
	"Teruslah membuat orang tersenyum. Rumah adalah tempat di mana aroma kue selalu menghangatkan hati.",
	"Air mata kebahagiaan jatuh perlahan.",
	"Ini bukan tentang keberhasilan…",
	"Ini tentang memahami makna dari setiap kue yang ia buat.",
	"Festival itu bukan akhir dari perjalanannya.",
	"Ini justru permulaan dari sesuatu yang lebih besar.",
	"Dan untuk pertama kalinya dalam bertahun-tahun… Bakery of Dreams benar-benar hidup kembali."
];


dialog_index = 0;